language: objective-c
before_script:
  - cd foodcritic
  - bundle install
script: "bundle exec foodcritic -f any -f ~FC004 -f ~FC005 -f ~FC015 -f ~FC017 .."
notifications:
  email:
    recipients:
      - chris@wideeyelabs.com
    on_success: change
    on_failure: always
