include_recipe "wel_station::create_var_chef_cache"
include_recipe "wel_station::sshd_on"
include_recipe "wel_station::firefox"
include_recipe "wel_station::dropbox"
include_recipe "wel_station::chrome"
include_recipe "wel_osx-settings::defaults_fast_key_repeat_rate"
inlcude_recipe "wel_osx-apps::cloud"
