include_recipe "wel_station::rvm"
include_recipe "wel_station::gem_setup"
include_recipe "wel_station::mysql"
include_recipe "wel_station::postgres"
include_recipe "wel_station::imagemagick"
include_recipe "wel_station::node_js"
include_recipe "wel_station::qt"
