maintainer        'Wide Eye Labs'
maintainer_email  'chris@wideeyelabs.com'
license           'MIT'
description       'Uses wel-station to configure an OSX workstation for development'
long_description  'Uses wel-station to configure an OSX workstation for development'
version           '0.1.0'
supports          'mac_os_x'
depends           'wel_station'
